name       : gtksourceviewmm
version    : 3.21.2
release    : 1
source     :
    - http://ftp.acc.umu.se/mirror/gnome.org/sources/gtksourceviewmm/3.21/gtksourceviewmm-3.21.2.tar.xz : d21296d8624a1046841bfec082021b7b966df0b62e19ee300828519bc54dd9c6
license    : LGPL-2.1
component  : desktop.gnome.core
summary    : C++ wrapper for gtksourceview
description: |
    C++ wrapper for gtksourceview
builddeps  :
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(gtkspellmm-3.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
