name       : gtksourceviewmm
version    : 3.21.3
release    : 6
source     :
    - https://download.gnome.org/sources/gtksourceviewmm/3.21/gtksourceviewmm-3.21.3.tar.xz : dbb00b1c28e0407cc27d8b07a2ed0b4ea22f92e4b3e3006431cbd6726b6256b5
license    : LGPL-2.1-only
component  : desktop.gnome.core
summary    : C++ wrapper for gtksourceview
description: |
    C++ wrapper for gtksourceview
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(gtkspellmm-3.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
